import { FakeBookDetail } from "@/app/books/actions";

const fakebooksInfo: FakeBookDetail[] = [
  {
    id: 1,
    title: "위대한 개츠비",
    author: "F. 스콧 피츠제럴드",
    description: "재즈 시대의 사랑과 배신에 관한 이야기.",
    publishedYear: 1925,
    genre: "고전",
  },
  {
    id: 2,
    title: "토지",
    author: "박경리",
    description: "한국 근현대사를 배경으로 한 대하소설.",
    publishedYear: 1969,
    genre: "대하소설",
  },
  {
    id: 3,
    title: "1984",
    author: "조지 오웰",
    description: "감시와 전체주의를 다룬 디스토피아 소설.",
    publishedYear: 1949,
    genre: "과학 소설",
  },
  {
    id: 4,
    title: "오만과 편견",
    author: "제인 오스틴",
    description: "영국 시골을 배경으로 한 로맨스 소설.",
    publishedYear: 1813,
    genre: "로맨스",
  },
  {
    id: 5,
    title: "호밀밭의 파수꾼",
    author: "J.D. 샐린저",
    description: "십대 소년의 반항과 고독을 그린 소설.",
    publishedYear: 1951,
    genre: "문학 소설",
  },
  {
    id: 6,
    title: "해리 포터와 마법사의 돌",
    author: "J.K. 롤링",
    description: "어린 마법사 해리 포터의 모험 이야기.",
    publishedYear: 1997,
    genre: "판타지",
  },
  {
    id: 7,
    title: "백년의 고독",
    author: "가브리엘 가르시아 마르케스",
    description: "마콘도 가문의 흥망성쇠를 그린 마술적 리얼리즘 소설.",
    publishedYear: 1967,
    genre: "마술적 리얼리즘",
  },
  {
    id: 8,
    title: "삼국지",
    author: "나관중",
    description: "중국 삼국 시대의 영웅들을 그린 역사 소설.",
    publishedYear: 1400,
    genre: "역사 소설",
  },
  {
    id: 9,
    title: "데미안",
    author: "헤르만 헤세",
    description: "청년의 내면적 성장과 자아 발견을 다룬 소설.",
    publishedYear: 1919,
    genre: "철학 소설",
  },
  {
    id: 10,
    title: "어린 왕자",
    author: "앙투안 드 생텍쥐페리",
    description: "어린 왕자의 순수한 시선으로 본 세상 이야기.",
    publishedYear: 1943,
    genre: "동화",
  },
  {
    id: 11,
    title: "노인과 바다",
    author: "어니스트 헤밍웨이",
    description: "한 노인의 바다에서의 투쟁과 인내를 그린 소설.",
    publishedYear: 1952,
    genre: "문학 소설",
  },
  {
    id: 12,
    title: "동물농장",
    author: "조지 오웰",
    description: "동물들이 인간을 몰아내고 만든 이상적인 사회의 이야기.",
    publishedYear: 1945,
    genre: "풍자 소설",
  },
  {
    id: 13,
    title: "좁은 문",
    author: "앙드레 지드",
    description: "사랑과 신앙 사이에서 갈등하는 한 여자의 이야기.",
    publishedYear: 1909,
    genre: "문학 소설",
  },
  {
    id: 14,
    title: "칼의 노래",
    author: "김훈",
    description: "이순신 장군의 삶과 전투를 그린 역사 소설.",
    publishedYear: 2001,
    genre: "역사 소설",
  },
  {
    id: 15,
    title: "태백산맥",
    author: "조정래",
    description: "한국 현대사의 격동기를 배경으로 한 대하소설.",
    publishedYear: 1989,
    genre: "대하소설",
  },
  {
    id: 16,
    title: "파우스트",
    author: "요한 볼프강 폰 괴테",
    description: "악마와의 계약을 통해 지식을 얻으려는 한 학자의 이야기.",
    publishedYear: 1808,
    genre: "비극",
  },
  {
    id: 17,
    title: "죄와 벌",
    author: "표도르 도스토옙스키",
    description: "범죄와 그에 따른 죄책감을 다룬 심리 소설.",
    publishedYear: 1866,
    genre: "심리 소설",
  },
  {
    id: 18,
    title: "달과 6펜스",
    author: "서머셋 몸",
    description: "예술을 위해 모든 것을 버린 한 화가의 이야기.",
    publishedYear: 1919,
    genre: "문학 소설",
  },
  {
    id: 19,
    title: "무정",
    author: "이광수",
    description: "한국 최초의 근대 소설로, 사랑과 배신을 그린 작품.",
    publishedYear: 1917,
    genre: "근대 소설",
  },
  {
    id: 20,
    title: "흙",
    author: "김동인",
    description: "한국 농촌의 삶과 인간성을 그린 소설.",
    publishedYear: 1932,
    genre: "리얼리즘 소설",
  },
  {
    id: 21,
    title: "광장",
    author: "최인훈",
    description: "한국 전쟁 이후의 분단 현실을 그린 소설.",
    publishedYear: 1960,
    genre: "현대 소설",
  },
  {
    id: 22,
    title: "서유기",
    author: "오승은",
    description: "손오공의 모험을 그린 중국 고전 소설.",
    publishedYear: 1699,
    genre: "고전 소설",
  },
  {
    id: 23,
    title: "변신",
    author: "프란츠 카프카",
    description: "한 남자가 아침에 깨어나 벌레로 변한 이야기.",
    publishedYear: 1915,
    genre: "실존주의 소설",
  },
  {
    id: 24,
    title: "젊은 베르테르의 슬픔",
    author: "요한 볼프강 폰 괴테",
    description: "사랑과 좌절을 그린 서간체 소설.",
    publishedYear: 1774,
    genre: "서간체 소설",
  },
  {
    id: 25,
    title: "안나 카레니나",
    author: "레프 톨스토이",
    description: "사랑과 배신, 사회적 규범을 다룬 소설.",
    publishedYear: 1877,
    genre: "리얼리즘 소설",
  },
  {
    id: 26,
    title: "성냥팔이 소녀",
    author: "한스 크리스티안 안데르센",
    description: "추운 겨울 밤, 성냥팔이 소녀의 슬픈 이야기.",
    publishedYear: 1845,
    genre: "동화",
  },
  {
    id: 27,
    title: "오디세이아",
    author: "호메로스",
    description: "오디세우스의 고향으로의 귀환을 그린 고대 서사시.",
    publishedYear: -800,
    genre: "서사시",
  },
  {
    id: 28,
    title: "레미제라블",
    author: "빅토르 위고",
    description: "프랑스 혁명 이후의 사회적 불평등을 그린 소설.",
    publishedYear: 1862,
    genre: "역사 소설",
  },
  {
    id: 29,
    title: "어린이의 발견",
    author: "마리아 몬테소리",
    description: "아이들의 교육과 성장에 관한 철학적 고찰.",
    publishedYear: 1948,
    genre: "교육학",
  },
  {
    id: 30,
    title: "인간 실격",
    author: "다자이 오사무",
    description: "자아의 붕괴와 사회적 부적응을 그린 소설.",
    publishedYear: 1948,
    genre: "자전적 소설",
  },
  {
    id: 31,
    title: "눈물",
    author: "김소월",
    description: "한국 현대 시인의 대표적인 시집.",
    publishedYear: 1925,
    genre: "시집",
  },
  {
    id: 32,
    title: "바람과 함께 사라지다",
    author: "마거릿 미첼",
    description: "미국 남북 전쟁을 배경으로 한 로맨스 소설.",
    publishedYear: 1936,
    genre: "역사 소설",
  },
  {
    id: 33,
    title: "작은 아씨들",
    author: "루이자 메이 올콧",
    description: "네 자매의 성장과 사랑을 그린 소설.",
    publishedYear: 1868,
    genre: "성장 소설",
  },
  {
    id: 34,
    title: "그리스인 조르바",
    author: "니코스 카잔차키스",
    description: "자유로운 영혼 조르바의 삶과 철학을 그린 소설.",
    publishedYear: 1946,
    genre: "철학 소설",
  },
];

export default fakebooksInfo;
